### PR TITLE
Use now(tz=utc) instead of deprecated utcnow

### PR DESCRIPTION
**Pull request by pcorpet**

### CODE REVIEW

**Review by nd4p90x — APPROVED** [review]

**Review by MichaelGHSeg — APPROVED** [review]

**Comment by DavidCain** [comment]
Thank you for this! @MichaelGHSeg - are there plans to release a new version of `segment-analytics-python` so it stops throwing deprecation warnings?

**Comment by nd4p90x** [comment]
We will begin work on that shortly, thank you!

**Comment by DavidCain** [comment]
@nd4p90x - any chance we could get a release? 😄

**Comment by nd4p90x** [comment]
> @nd4p90x - any chance we could get a release? 😄

Yes, we were waiting on a few items to be completed first

I will be working on the release this coming week.

Thank you!

**Pull request merged**
