### PR TITLE
Rename package name from "analytics" to "segment"

### PR DESCRIPTION
**Pull request by alvinchow86**
The top-level package name really should be something unique, like **segment** or **segmentio** or something. If you have another package or module loaded in your Python load path named analytics, a very common word, there is a name-space collision and it's possible (or very difficult) to resolve in Python. A common case this happens is with Django, if you follow the standard documentation and make an app called `analytics` that's a top-level import.

``` python
# import analytics
import segmentio
```

This PR renames the module from `analytics` to `segment`. I would probably also rename the setuptools name to segment-python or something but left it alone for now.

Related #42

### CODE REVIEW

**Comment by stevenmiller888** [comment]
cc/ @ivolo @calvinfo ^

**Comment by alvinchow86** [comment]
any thoughts or update about this? the top-level package should really be renamed

related issue https://github.com/segmentio/analytics-python/issues/42

**Comment by hendra-doordash** [comment]
are there anything using this package? Other than that lgtm

**Comment by diwu1989** [comment]
+1 i think it should be named segmentio

**Comment by diwu1989** [comment]
it might be even better to just publish a new package completely as `segment-python` vs `analytics-python`

**Comment by f2prateek** [comment]
Closing for https://github.com/segmentio/analytics-python/pull/82

**Pull request closed without merging**
