### PR TITLE
Don't add messages to the queue if send is false

### LINKED ISSUE #85: analytics.flush can hang forever if analytics.send == False
Calling `analytics.flush()` makes the shell hang forever, even keyboard interrupts don't work.

```
In [1]: import analytics

In [2]: analytics.write_key = 'TEST_WRITE_KEY'

In [3]: analytics.send = False

In [4]: analytics.track('fake_user_id', 'Sent Email')

In [5]: analytics.flush()
^C^C^C^C^C^C
```

Two alternative options how to improve the behavior if `analytics.send` is set to `False`:
1. `Client._enqueue` should never put items into the queue (it still makes sense to do everything else that that method does so that its behavior can be covered by unit tests).
2. Let `Client.flush` return immediately or raise an exception saying that flush won't work if `send` is `False` because the consumer is not running.

Personally I prefer the 1st option.

### PR DESCRIPTION
**Pull request by wojcikstefan**
Fixes #85

### CODE REVIEW

**Comment by f2prateek** [comment]
Oh this makes more sense! LGTM

cc @jgershen @calvinfo

**Comment by f2prateek** [comment]
@wojcikstefan  CI issues should be fixed - could you rebase so we can re-run CI?

**Comment by wojcikstefan** [comment]
done @f2prateek

**Comment by wojcikstefan** [comment]
@f2prateek is there anything else you need from me before merging this?

**Comment by f2prateek** [comment]
@wojcikstefan nope - just waiting for either @calvinfo or @jgershen to review!

**Comment by jgershen** [comment]
Sorry, been languishing in my inbox. LGTM; thanks @wojcikstefan !

**Pull request merged**
