### PR TITLE
Date objects fail json serialization

### PR DESCRIPTION
**Pull request by hadrien**
Fix segmentio/analytics-python#91

### CODE REVIEW

**Comment by alexissmirnov** [comment]
+1

**Comment by hadrien** [comment]
Who should/can review this @jgershen? Thanks!

**Comment by f2prateek** [comment]
Sorry for the delay, this looks good to me! Would love to have @jgershen and/or @calvinfo review as well.

**Comment by calvinfo** [comment]
LGTM! Thanks both of you!

**Comment by hadrien** [comment]
Excellent!
How much time should we expect before release?

Sorry to push forward and thanks a lot for the support!

**Comment by f2prateek** [comment]
I'll likely br able to release this sometime next week.

**Comment by hadrien** [comment]
Please, can you release the v1.2.7? I am looking forward it ! ;-) Thanks a lot!

**Comment by hadrien** [comment]
It is actually released: https://pypi.python.org/pypi/analytics-python/1.2.7

My bad sorry! thanks a lot!

**Pull request merged**
