### PR TITLE
Issue #344 fix tests

### PR DESCRIPTION
**Pull request by nd4p90x**
Update the github actions to include loading of application requirements file and execute tests for each version

### CODE REVIEW

**Comment by nd4p90x** [comment]
@MichaelGHSeg Please review and confirm test action is completing after update.  Thank you.

**Comment by MichaelGHSeg** [comment]
Looks like it's only running the 8 tests in segment/analytics/test/__init__.py
I feel like the easiest way to do this might be to move the contents of __init__.py (without the hack to run other test files that doesn't seem to work) to a differently named file and make __init__.py blank.  Some things I read said a blank init would have it run everything.

**Comment by MichaelGHSeg** [comment]
OAuth is working as intended, the tests that make sure exceptions are handled are just noisy.

The utility tests seem to have what I'm guessing is a python3 problem where datetimes, exceptions, and functions aren't serializable when they once were?  It ends up just leaving them out of the output and comparison datasets so it still passes, but we could clean that up.

**Comment by nd4p90x** [comment]
@MichaelGHSeg Removal of that requirement you suggested worked, ready to move forward.

Thanks,

**Review by MichaelGHSeg — APPROVED** [review]

**Pull request merged**
